name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]  # Cambia a "master" si es tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Usa la versión de Node.js que necesites

      - name: Install dependencies
        run: npm install

      - name: Build with RsBuild
        run: npm run build  # Asegúrate de que este comando genera los archivos en /dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist